name: Deploy Waiter on Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Déploiement via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Bistro-Tech/Waiter || exit 1
            sudo docker stop waiter
            sudo docker rm waiter || true
            git pull origin main
            sudo docker build -t waiter .
            sudo docker run --env-file .env -d --name waiter waiter
